
footer = document.getElementById('footer');


innerHTML ='<div class="container-fluid bg-dark text-light footer mt-5 pt-5 wow fadeIn" data-wow-delay="0.1s">'
innerHTML +='        <div class="container py-5">'
innerHTML +='            <div class="row g-5">'
innerHTML +='                <div class="col-lg-3 col-md-6">'
innerHTML +='                    <h4 class="text-light mb-4">Address</h4>'
innerHTML +='                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>1/44, Shop No-3.Whs, Kirti Nagar, New Delhi</p>'
innerHTML +='                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91 11 41420874</p>'
innerHTML +='                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info.jailaxmi@gmail.com</p>'
innerHTML +='                    <div class="d-flex pt-2">'
innerHTML +='                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>'
innerHTML +='                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>'
innerHTML +='                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>'
innerHTML +='                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>'
innerHTML +='                    </div>'
innerHTML +='                </div>'
innerHTML +='                <div class="col-lg-3 col-md-6">'
innerHTML +='                    <h4 class="text-light mb-4">Products</h4>'
innerHTML +='                    <a class="btn btn-link" href="kitchen.html">Kitchen Hardware</a>'
innerHTML +='                    <a class="btn btn-link" href="glass.html">Glass Hardware</a>'
innerHTML +='                    <a class="btn btn-link" href="furniture.html">Furniture Hardware</a>'
innerHTML +='                    <a class="btn btn-link" href="AluminumProfiles.html">Aluminum Profiles</a>'
innerHTML +='                </div>'
innerHTML +='                <div class="col-lg-3 col-md-6">'
innerHTML +='                    <h4 class="text-light mb-4">Quick Links</h4>'
innerHTML +='                    <a class="btn btn-link" href="">About Us</a>'
innerHTML +='                    <a class="btn btn-link" href="">Contact Us</a>'
//innerHTML +='                    <a class="btn btn-link" href="">Our Services</a>'
//innerHTML +='                    <a class="btn btn-link" href="">Terms & Condition</a>'
//innerHTML +='                    <a class="btn btn-link" href="">Support</a>'
innerHTML +='                </div>'
innerHTML +='                <div class="col-lg-3 col-md-6">'
//innerHTML +='                    <h4 class="text-light mb-4">Newsletter</h4>'
//innerHTML +='                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>'
//innerHTML +='                    <div class="position-relative mx-auto" style="max-width: 400px;">'
//innerHTML +='                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">'
//innerHTML +='                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>'
//innerHTML +='                    </div>'
innerHTML +='                </div>'
innerHTML +='            </div>'
innerHTML +='        </div>'
innerHTML +='        <div class="container">'
innerHTML +='            <div class="copyright">'
innerHTML +='                <div class="row">'
innerHTML +='                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">'
innerHTML +='                        &copy; <a class="border-bottom" href="#">www.stylushardware.com</a>, All Right Reserved.'
innerHTML +='                    </div>'
innerHTML +='                    <div class="col-md-6 text-center text-md-end">'
innerHTML +='                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you\'d like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->'
innerHTML +='                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>'
innerHTML +='                    </div>'
innerHTML +='                </div>'
innerHTML +='            </div>'
innerHTML +='        </div>'
innerHTML +='    </div>'

footer.innerHTML = innerHTML